version: '3.9'

services:
  sonarqube-db:
    image: postgres:latest
    container_name: postgres-sonarqube
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonar-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-server
    ports:
      - "9999:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar_pass
    depends_on:
      - sonarqube-db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar-network

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  sonar-network:
    driver: bridge

